### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jacquesmatcgithub/myMovies#1]
Good work! Just a question:

- [x] Is this method needed? It seems like the other methods that allow you send in a property and a value to search by cover this case? (I had it in the demo for demonstration purposes only). https://github.com/jacquesmatcgithub/myMovies/blob/c14c137010382b65621fd02dfd50555dfddecfaa/src/main/java/edu/matc/persistence/UserDao.java#L40-L56

**Comment by jacquesmatcgithub** [comment]
Thanks Paula!   will remove that method. I don't need it.
