### ISSUE TITLE
Instructor Feedback - Checkpoint 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jacquesmatcgithub/myMovies#5]
Great job getting so much functionality up and running already - particularly the service implementation! I'm glad to see you are keeping up to date with your time log, and it was helpful to be able to see what your sticking points have been.

I know you are actively working on this, and may already have many of these items on your radar, but just in case...

- [ ] Typically we try to avoid using server side scripting like this: https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/webapp/content-movie-grid.jsp#L5-L7, in favor of using javabeans.  
- [ ] HTML is mixed into java code here. Is it possible to refactor so that the html is in a jsp? https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/controller/GenerateMovieGrid.java#L70-L72
- [x] Is there an opportunity to refactor this into something reusable? https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/controller/ClickedThumb.java#L61-L77 and https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/controller/ClickedRating.java#L44-L59
- [x] As you work on refactoring, remember to move hard-coded values into a property file so that the value is easy to maintain: https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/controller/TmdbJsonService.java#L21
- [x] As you work through the Week 9 exercise, think about whether the parsing in this class is needed: https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/controller/TmdbJsonService.java#L14
- [x] Could the generic dao be used instead of  https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/persistence/MetadataTmdbDao.java#L15 and https://github.com/jacquesmatcgithub/myMovies/blob/30081dd06b37fc41451cf1d384ccc57a37e25fe6/src/main/java/edu/matc/persistence/MovieDao.java#L16
- [x] Seems like some of the classes in the Persistence package could be moved to Entity?

**Comment by jacquesmatcgithub** [comment]
I've done a lot of refactoring. The server side scripting was supposed to be turned into a custom tag lib at some point, but time caught up with me unfortunately. I also really wanted to incorporate a generic dao for everything, but the time just was not there.
