### ISSUE TITLE
peer code review

### ISSUE THREAD

**Issue by ricabruinsma** [jacquesmatcgithub/myMovies#6]
# Design/Code Review 3

#### Reviewer: Rica Bruinsma

<hr /><hr />

#### I wasn't sure about what Paula meant by a lot of these code quality questions - so Paula sat with me as I went through a few of your Java classes.  As you might guess, there are more comments/suggestions than I would have originally offered.<hr /><hr />

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? | well-developed UI, login, authentication, create/read/update on admin/collector, CRUD on movies, Web Services consumed & displayed, DB accessed with java -- Really beautiful!!! |
|| What planned functionality has not been met? | delete on admin/collector, update DB ERD diagram, deploy latest web app to AWS, update app link in student repo, time permitting - recommend movies based on current weather, implement Generic Dao (Paula said she would take a few points for this) |
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| Steady progress throughout semester! Way to go!! |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| Most issues addressed, some in progress still (Generic Dao is one) |
||Other comments/notes?| Really gorgeous UI!  Nice implementation of movie database API and weather API.  There are a lot of special touches - which are nice. |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| Nice use of templates.  Data validation handled in CRUD classes (not jsps). Really nice look and feel. |
||Other comments/notes?| is content-user.jsp being used? |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | <li> AdminPage populate function - could you refactor and pass in the User object, rather than each attribute? <li>GenerateMovieSelectGrid.java line 69, 82, 88, 94, 105, 110, 112 has out.print function - I think Paula might take off points for this <li>some jdoc present, some copy/paste error (MetadataTmdb.java line 7, PrepareCollectorPage.java lines 19-21) <li>some classes perform multiple functions. could think about refactoring. <li>nice naming of methods, classes, packages, variables. <li>properties file implemented. <li>exceptions handled. <li>Note: I only did a spot check of a few controller, entity, and persistence classes. |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|<li>logger used mainly for debugging <li>no System.out.println() or printStackTrace() |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After | <li>CleanupUserMovieCatalogTest.java looks incomplete <li>want to make sure to test movie recommendations when it's up and running<li>specific Dao tests look good.
| |Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| tomcat authentication is in place |
||Is it implemented correctly and working locally as well as on AWS? | local version implemented correctly.  outdated version deployed to AWS is working correctly |
||Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is error handling of the service implemented? For example, what happens if the service is not available?| <li>https://api.themoviedb.org <li>http://api.wunderground.com/api <li>error handling for if service not available or doesn't return info  |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| implementing two different web services  |
||Is the independent research topic/technique implemented in the project?| yes |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| Yes, though the latest code has not yet been deployed |
||Is the hosted application fully functioning?| very close... |
||Other comments/notes?| |

**Comment by jacquesmatcgithub** [comment]
Thanks for the great review. I just wish I had a couple weeks more to implement some of the suggestions.
