### ISSUE TITLE
Instructor Feedback - Week 14

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jacquesmatcgithub/myMovies#7]
Hi @jacquesmatcgithub. Wow! You've really put in a lot of work here! I thought a quick review might be helpful as you put the polish on your application.  One thing I noticed recurring is a large number of params passed into methods (often a result of using intelliJ's refactor capabilities). Examine the methods with long param lists to determine if they can be simplified - a few examples are highlighted below along with a few other issues I noticed.

- [ ] Could this https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/AdminPage.java#L55-L67 be simplified by passing the User, rather than each instance variable on the user?  The would also simplify this portion: https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/AdminPage.java#L102-L108, so you could simply put the User in the request.
- [ ] Here you are getting a Movie object out of the list and then creating a new movie object, setting each value. https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/SuggestMovie.java#L69-L70. Could it be simplified to:
```
for (Movie thisMovie : movies) {
                    thismovie.setWhateverthisvalueis("SU");
                   movieDao.saveOrUpdate(thisMovie);

```
- [ ] Rather than passing in weatherConditions and currentSeason, simplify by calling the methods to get these values when you actually need them. https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/Suggest.java#L72-L76
- [ ] Is this information used only for a single user (use session) or all users (use servlet context which provides application scope)? https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/AppConfig.java#L58-L62
- [ ] Is this needed? https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/GenerateMovieGrid.java#L66-L68
- [ ] Could this be accomplished using the core tags in the jsp? You had commented in an earlier issue that you considered a custom tag for this, but I'm wondering if the core tags would do it? https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/java/edu/matc/controller/GenerateMovieGrid.java#L72-L99
- [ ] Opportunity for front end validation on some forms: https://github.com/jacquesmatcgithub/myMovies/blob/3b90f3b90f81cbccca866a08605edd7d62542fcf/src/main/webapp/content-new-user.jsp#L11-L22

**Comment by jacquesmatcgithub** [comment]
Thanks for the great suggestions Paula.  I will keep working on this project in the coming weeks/months to keep things fresh in my head until my company can start using us for java work.

**Comment by jacquesmatcgithub** [comment]
I am closing this issue, but will use Paula's suggestions to improve my app.
